### ISSUE TITLE
Simulator doesn't unbind navigator's keys

### ISSUE THREAD

**Issue by RedGl0w** [Omega-Numworks/omega-numworks.github.io#55]
When using the arrows keys on simulator, the whole page is sliding, making it unusable.
![Peek 16-03-2021 07-50](https://user-images.githubusercontent.com/43498612/111267544-581e5d00-862c-11eb-995b-7f872444df5f.gif)

**Comment by quentinguidee** [comment]
Seems to be fixed by this commit 25 days ago : 20de97397f342ce1c862576b69ed0ab56f8975d7

**Comment by RedGl0w** [comment]
Yep this issue is fixed, but now there isn't any alpha-numeric key working
